// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/approvals": {
    params: {};
  };
  "/admin/ai/console": {
    params: {};
  };
  "/admin/ai/budget": {
    params: {};
  };
  "/admin/ai/runs/:id": {
    params: {
      "id": string;
    };
  };
  "/ledger/reports/:report": {
    params: {
      "report": string;
    };
  };
  "/ledger/transactions": {
    params: {};
  };
  "/ledger/transactions/:id": {
    params: {
      "id": string;
    };
  };
  "/ledger/period-close": {
    params: {};
  };
  "/ledger/statement": {
    params: {};
  };
  "/ledger/recon": {
    params: {};
  };
  "/analytics/report/:id": {
    params: {
      "id": string;
    };
  };
  "/analytics/dashboard/:id": {
    params: {
      "id": string;
    };
  };
  "/distribution/quote-requests/:id/compare": {
    params: {
      "id": string;
    };
  };
  "/orbit/conversations/:id/thread": {
    params: {
      "id": string;
    };
  };
  "/distribution/commission-entries/statement": {
    params: {};
  };
  "/distribution/commission-entries/:id/clawback": {
    params: {
      "id": string;
    };
  };
  "/distribution/next-best-offers/suggest": {
    params: {};
  };
  "/compliance/run/:kind": {
    params: {
      "kind": string;
    };
  };
  "/ledger/settlement": {
    params: {};
  };
  "/ledger/settlements/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/staff": {
    params: {};
  };
  "/admin/staff/:id": {
    params: {
      "id": string;
    };
  };
  "/:module": {
    params: {
      "module": string;
    };
  };
  "/:module/:resource": {
    params: {
      "module": string;
      "resource": string;
    };
  };
  "/:module/:resource/:id": {
    params: {
      "module": string;
      "resource": string;
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/settings" | "/approvals" | "/admin/ai/console" | "/admin/ai/budget" | "/admin/ai/runs/:id" | "/ledger/reports/:report" | "/ledger/transactions" | "/ledger/transactions/:id" | "/ledger/period-close" | "/ledger/statement" | "/ledger/recon" | "/analytics/report/:id" | "/analytics/dashboard/:id" | "/distribution/quote-requests/:id/compare" | "/orbit/conversations/:id/thread" | "/distribution/commission-entries/statement" | "/distribution/commission-entries/:id/clawback" | "/distribution/next-best-offers/suggest" | "/compliance/run/:kind" | "/ledger/settlement" | "/ledger/settlements/:id" | "/admin/staff" | "/admin/staff/:id" | "/:module" | "/:module/:resource" | "/:module/:resource/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/workspace.tsx": {
    id: "routes/workspace";
    page: "/" | "/settings" | "/approvals" | "/admin/ai/console" | "/admin/ai/budget" | "/admin/ai/runs/:id" | "/ledger/reports/:report" | "/ledger/transactions" | "/ledger/transactions/:id" | "/ledger/period-close" | "/ledger/statement" | "/ledger/recon" | "/analytics/report/:id" | "/analytics/dashboard/:id" | "/distribution/quote-requests/:id/compare" | "/orbit/conversations/:id/thread" | "/distribution/commission-entries/statement" | "/distribution/commission-entries/:id/clawback" | "/distribution/next-best-offers/suggest" | "/compliance/run/:kind" | "/ledger/settlement" | "/ledger/settlements/:id" | "/admin/staff" | "/admin/staff/:id" | "/:module" | "/:module/:resource" | "/:module/:resource/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/approvals.tsx": {
    id: "routes/approvals";
    page: "/approvals";
  };
  "routes/ai-console.tsx": {
    id: "routes/ai-console";
    page: "/admin/ai/console";
  };
  "routes/ai-budget.tsx": {
    id: "routes/ai-budget";
    page: "/admin/ai/budget";
  };
  "routes/ai-run.tsx": {
    id: "routes/ai-run";
    page: "/admin/ai/runs/:id";
  };
  "routes/ledger-reports.tsx": {
    id: "routes/ledger-reports";
    page: "/ledger/reports/:report";
  };
  "routes/ledger-open-txn.tsx": {
    id: "routes/ledger-open-txn";
    page: "/ledger/transactions";
  };
  "routes/ledger-transaction.tsx": {
    id: "routes/ledger-transaction";
    page: "/ledger/transactions/:id";
  };
  "routes/ledger-periods.tsx": {
    id: "routes/ledger-periods";
    page: "/ledger/period-close";
  };
  "routes/ledger-account.tsx": {
    id: "routes/ledger-account";
    page: "/ledger/statement";
  };
  "routes/ledger-recon.tsx": {
    id: "routes/ledger-recon";
    page: "/ledger/recon";
  };
  "routes/analytics-report.tsx": {
    id: "routes/analytics-report";
    page: "/analytics/report/:id";
  };
  "routes/analytics-dashboard.tsx": {
    id: "routes/analytics-dashboard";
    page: "/analytics/dashboard/:id";
  };
  "routes/quote-compare.tsx": {
    id: "routes/quote-compare";
    page: "/distribution/quote-requests/:id/compare";
  };
  "routes/conversation.tsx": {
    id: "routes/conversation";
    page: "/orbit/conversations/:id/thread";
  };
  "routes/commission-statement.tsx": {
    id: "routes/commission-statement";
    page: "/distribution/commission-entries/statement";
  };
  "routes/commission-clawback.tsx": {
    id: "routes/commission-clawback";
    page: "/distribution/commission-entries/:id/clawback";
  };
  "routes/dist-offers.tsx": {
    id: "routes/dist-offers";
    page: "/distribution/next-best-offers/suggest";
  };
  "routes/compliance-run.tsx": {
    id: "routes/compliance-run";
    page: "/compliance/run/:kind";
  };
  "routes/settlement.tsx": {
    id: "routes/settlement";
    page: "/ledger/settlement";
  };
  "routes/settlement-detail.tsx": {
    id: "routes/settlement-detail";
    page: "/ledger/settlements/:id";
  };
  "routes/staff.tsx": {
    id: "routes/staff";
    page: "/admin/staff";
  };
  "routes/staff-member.tsx": {
    id: "routes/staff-member";
    page: "/admin/staff/:id";
  };
  "routes/module.tsx": {
    id: "routes/module";
    page: "/:module";
  } | {
    id: "module-resource";
    page: "/:module/:resource";
  };
  "routes/record.tsx": {
    id: "routes/record";
    page: "/:module/:resource/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/workspace": typeof import("./app/routes/workspace.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/approvals": typeof import("./app/routes/approvals.tsx");
  "routes/ai-console": typeof import("./app/routes/ai-console.tsx");
  "routes/ai-budget": typeof import("./app/routes/ai-budget.tsx");
  "routes/ai-run": typeof import("./app/routes/ai-run.tsx");
  "routes/ledger-reports": typeof import("./app/routes/ledger-reports.tsx");
  "routes/ledger-open-txn": typeof import("./app/routes/ledger-open-txn.tsx");
  "routes/ledger-transaction": typeof import("./app/routes/ledger-transaction.tsx");
  "routes/ledger-periods": typeof import("./app/routes/ledger-periods.tsx");
  "routes/ledger-account": typeof import("./app/routes/ledger-account.tsx");
  "routes/ledger-recon": typeof import("./app/routes/ledger-recon.tsx");
  "routes/analytics-report": typeof import("./app/routes/analytics-report.tsx");
  "routes/analytics-dashboard": typeof import("./app/routes/analytics-dashboard.tsx");
  "routes/quote-compare": typeof import("./app/routes/quote-compare.tsx");
  "routes/conversation": typeof import("./app/routes/conversation.tsx");
  "routes/commission-statement": typeof import("./app/routes/commission-statement.tsx");
  "routes/commission-clawback": typeof import("./app/routes/commission-clawback.tsx");
  "routes/dist-offers": typeof import("./app/routes/dist-offers.tsx");
  "routes/compliance-run": typeof import("./app/routes/compliance-run.tsx");
  "routes/settlement": typeof import("./app/routes/settlement.tsx");
  "routes/settlement-detail": typeof import("./app/routes/settlement-detail.tsx");
  "routes/staff": typeof import("./app/routes/staff.tsx");
  "routes/staff-member": typeof import("./app/routes/staff-member.tsx");
  "routes/module": typeof import("./app/routes/module.tsx");
  "module-resource": typeof import("./app/routes/module.tsx");
  "routes/record": typeof import("./app/routes/record.tsx");
};