// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/portal/:tenantSlug": {
    params: {
      "tenantSlug": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/approvals": {
    params: {};
  };
  "/admin/ai/console": {
    params: {};
  };
  "/admin/ai/budget": {
    params: {};
  };
  "/admin/ai/runs/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/cost-explorer": {
    params: {};
  };
  "/ledger/reports/:report": {
    params: {
      "report": string;
    };
  };
  "/ledger/money-map": {
    params: {};
  };
  "/ledger/transactions": {
    params: {};
  };
  "/ledger/transactions/:id": {
    params: {
      "id": string;
    };
  };
  "/ledger/period-close": {
    params: {};
  };
  "/ledger/statement": {
    params: {};
  };
  "/ledger/recon": {
    params: {};
  };
  "/analytics/report/:id": {
    params: {
      "id": string;
    };
  };
  "/analytics/dashboard/:id": {
    params: {
      "id": string;
    };
  };
  "/distribution/quote-requests/:id/compare": {
    params: {
      "id": string;
    };
  };
  "/orbit/conversations/:id/thread": {
    params: {
      "id": string;
    };
  };
  "/distribution/commission-entries/statement": {
    params: {};
  };
  "/distribution/commission-entries/:id/clawback": {
    params: {
      "id": string;
    };
  };
  "/distribution/next-best-offers/suggest": {
    params: {};
  };
  "/compliance/run/:kind": {
    params: {
      "kind": string;
    };
  };
  "/ledger/settlement": {
    params: {};
  };
  "/ledger/settlements/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/permissions": {
    params: {};
  };
  "/admin/developer": {
    params: {};
  };
  "/admin/security": {
    params: {};
  };
  "/admin/staff": {
    params: {};
  };
  "/admin/staff/:id": {
    params: {
      "id": string;
    };
  };
  "/platform": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/search/results": {
    params: {};
  };
  "/onboarding/:kind/:ref": {
    params: {
      "kind": string;
      "ref": string;
    };
  };
  "/orbit/console": {
    params: {};
  };
  "/orbit/save": {
    params: {};
  };
  "/orbit/pipeline": {
    params: {};
  };
  "/orbit/quality": {
    params: {};
  };
  "/orbit/analytics": {
    params: {};
  };
  "/north/brief": {
    params: {};
  };
  "/scout/radar": {
    params: {};
  };
  "/scout/panel": {
    params: {};
  };
  "/axis/exceptions": {
    params: {};
  };
  "/axis/board": {
    params: {};
  };
  "/axis/quote-desk": {
    params: {};
  };
  "/axis/doc-intelligence": {
    params: {};
  };
  "/axis/documents/:id/file": {
    params: {
      "id": string;
    };
  };
  "/axis/analytics": {
    params: {};
  };
  "/axis/admin": {
    params: {};
  };
  "/axis/dev": {
    params: {};
  };
  "/axis/process-map": {
    params: {};
  };
  "/axis/claims/new": {
    params: {};
  };
  "/axis/claims/desk": {
    params: {};
  };
  "/axis/renewals": {
    params: {};
  };
  "/signal/cockpit": {
    params: {};
  };
  "/signal/studio": {
    params: {};
  };
  "/signal/audience-value": {
    params: {};
  };
  "/signal/answer-engines": {
    params: {};
  };
  "/signal/budget": {
    params: {};
  };
  "/signal/analytics": {
    params: {};
  };
  "/admin/customers/:id/360": {
    params: {
      "id": string;
    };
  };
  "/admin/products/:id/detail": {
    params: {
      "id": string;
    };
  };
  "/axis/policies/:id/detail": {
    params: {
      "id": string;
    };
  };
  "/axis/policies/:id/endorse": {
    params: {
      "id": string;
    };
  };
  "/axis/policies/:id/cancel": {
    params: {
      "id": string;
    };
  };
  "/axis/claims/:id/detail": {
    params: {
      "id": string;
    };
  };
  "/axis/cases/:id/evidence-bundles/:bundleId/download": {
    params: {
      "id": string;
      "bundleId": string;
    };
  };
  "/axis/cases/:id/detail": {
    params: {
      "id": string;
    };
  };
  "/distribution/channels/:id/detail": {
    params: {
      "id": string;
    };
  };
  "/orbit/journeys/:id/builder": {
    params: {
      "id": string;
    };
  };
  "/:module": {
    params: {
      "module": string;
    };
  };
  "/:module/:resource": {
    params: {
      "module": string;
      "resource": string;
    };
  };
  "/:module/:resource/:id": {
    params: {
      "module": string;
      "resource": string;
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/portal/:tenantSlug" | "/settings" | "/approvals" | "/admin/ai/console" | "/admin/ai/budget" | "/admin/ai/runs/:id" | "/admin/cost-explorer" | "/ledger/reports/:report" | "/ledger/money-map" | "/ledger/transactions" | "/ledger/transactions/:id" | "/ledger/period-close" | "/ledger/statement" | "/ledger/recon" | "/analytics/report/:id" | "/analytics/dashboard/:id" | "/distribution/quote-requests/:id/compare" | "/orbit/conversations/:id/thread" | "/distribution/commission-entries/statement" | "/distribution/commission-entries/:id/clawback" | "/distribution/next-best-offers/suggest" | "/compliance/run/:kind" | "/ledger/settlement" | "/ledger/settlements/:id" | "/admin/permissions" | "/admin/developer" | "/admin/security" | "/admin/staff" | "/admin/staff/:id" | "/platform" | "/search" | "/search/results" | "/onboarding/:kind/:ref" | "/orbit/console" | "/orbit/save" | "/orbit/pipeline" | "/orbit/quality" | "/orbit/analytics" | "/north/brief" | "/scout/radar" | "/scout/panel" | "/axis/exceptions" | "/axis/board" | "/axis/quote-desk" | "/axis/doc-intelligence" | "/axis/documents/:id/file" | "/axis/analytics" | "/axis/admin" | "/axis/dev" | "/axis/process-map" | "/axis/claims/new" | "/axis/claims/desk" | "/axis/renewals" | "/signal/cockpit" | "/signal/studio" | "/signal/audience-value" | "/signal/answer-engines" | "/signal/budget" | "/signal/analytics" | "/admin/customers/:id/360" | "/admin/products/:id/detail" | "/axis/policies/:id/detail" | "/axis/policies/:id/endorse" | "/axis/policies/:id/cancel" | "/axis/claims/:id/detail" | "/axis/cases/:id/evidence-bundles/:bundleId/download" | "/axis/cases/:id/detail" | "/distribution/channels/:id/detail" | "/orbit/journeys/:id/builder" | "/:module" | "/:module/:resource" | "/:module/:resource/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/portal.$tenantSlug.tsx": {
    id: "routes/portal.$tenantSlug";
    page: "/portal/:tenantSlug";
  };
  "routes/workspace.tsx": {
    id: "routes/workspace";
    page: "/" | "/settings" | "/approvals" | "/admin/ai/console" | "/admin/ai/budget" | "/admin/ai/runs/:id" | "/admin/cost-explorer" | "/ledger/reports/:report" | "/ledger/money-map" | "/ledger/transactions" | "/ledger/transactions/:id" | "/ledger/period-close" | "/ledger/statement" | "/ledger/recon" | "/analytics/report/:id" | "/analytics/dashboard/:id" | "/distribution/quote-requests/:id/compare" | "/orbit/conversations/:id/thread" | "/distribution/commission-entries/statement" | "/distribution/commission-entries/:id/clawback" | "/distribution/next-best-offers/suggest" | "/compliance/run/:kind" | "/ledger/settlement" | "/ledger/settlements/:id" | "/admin/permissions" | "/admin/developer" | "/admin/security" | "/admin/staff" | "/admin/staff/:id" | "/platform" | "/search" | "/search/results" | "/onboarding/:kind/:ref" | "/orbit/console" | "/orbit/save" | "/orbit/pipeline" | "/orbit/quality" | "/orbit/analytics" | "/north/brief" | "/scout/radar" | "/scout/panel" | "/axis/exceptions" | "/axis/board" | "/axis/quote-desk" | "/axis/doc-intelligence" | "/axis/documents/:id/file" | "/axis/analytics" | "/axis/admin" | "/axis/dev" | "/axis/process-map" | "/axis/claims/new" | "/axis/claims/desk" | "/axis/renewals" | "/signal/cockpit" | "/signal/studio" | "/signal/audience-value" | "/signal/answer-engines" | "/signal/budget" | "/signal/analytics" | "/admin/customers/:id/360" | "/admin/products/:id/detail" | "/axis/policies/:id/detail" | "/axis/policies/:id/endorse" | "/axis/policies/:id/cancel" | "/axis/claims/:id/detail" | "/axis/cases/:id/evidence-bundles/:bundleId/download" | "/axis/cases/:id/detail" | "/distribution/channels/:id/detail" | "/orbit/journeys/:id/builder" | "/:module" | "/:module/:resource" | "/:module/:resource/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/approvals.tsx": {
    id: "routes/approvals";
    page: "/approvals";
  };
  "routes/ai-console.tsx": {
    id: "routes/ai-console";
    page: "/admin/ai/console";
  };
  "routes/ai-budget.tsx": {
    id: "routes/ai-budget";
    page: "/admin/ai/budget";
  };
  "routes/ai-run.tsx": {
    id: "routes/ai-run";
    page: "/admin/ai/runs/:id";
  };
  "routes/cost-explorer.tsx": {
    id: "routes/cost-explorer";
    page: "/admin/cost-explorer";
  };
  "routes/ledger-reports.tsx": {
    id: "routes/ledger-reports";
    page: "/ledger/reports/:report";
  };
  "routes/ledger-money-map.tsx": {
    id: "routes/ledger-money-map";
    page: "/ledger/money-map";
  };
  "routes/ledger-open-txn.tsx": {
    id: "routes/ledger-open-txn";
    page: "/ledger/transactions";
  };
  "routes/ledger-transaction.tsx": {
    id: "routes/ledger-transaction";
    page: "/ledger/transactions/:id";
  };
  "routes/ledger-periods.tsx": {
    id: "routes/ledger-periods";
    page: "/ledger/period-close";
  };
  "routes/ledger-account.tsx": {
    id: "routes/ledger-account";
    page: "/ledger/statement";
  };
  "routes/ledger-recon.tsx": {
    id: "routes/ledger-recon";
    page: "/ledger/recon";
  };
  "routes/analytics-report.tsx": {
    id: "routes/analytics-report";
    page: "/analytics/report/:id";
  };
  "routes/analytics-dashboard.tsx": {
    id: "routes/analytics-dashboard";
    page: "/analytics/dashboard/:id";
  };
  "routes/quote-compare.tsx": {
    id: "routes/quote-compare";
    page: "/distribution/quote-requests/:id/compare";
  };
  "routes/conversation.tsx": {
    id: "routes/conversation";
    page: "/orbit/conversations/:id/thread";
  };
  "routes/commission-statement.tsx": {
    id: "routes/commission-statement";
    page: "/distribution/commission-entries/statement";
  };
  "routes/commission-clawback.tsx": {
    id: "routes/commission-clawback";
    page: "/distribution/commission-entries/:id/clawback";
  };
  "routes/dist-offers.tsx": {
    id: "routes/dist-offers";
    page: "/distribution/next-best-offers/suggest";
  };
  "routes/compliance-run.tsx": {
    id: "routes/compliance-run";
    page: "/compliance/run/:kind";
  };
  "routes/settlement.tsx": {
    id: "routes/settlement";
    page: "/ledger/settlement";
  };
  "routes/settlement-detail.tsx": {
    id: "routes/settlement-detail";
    page: "/ledger/settlements/:id";
  };
  "routes/admin-roles.tsx": {
    id: "routes/admin-roles";
    page: "/admin/permissions";
  };
  "routes/admin-developer.tsx": {
    id: "routes/admin-developer";
    page: "/admin/developer";
  };
  "routes/admin-security.tsx": {
    id: "routes/admin-security";
    page: "/admin/security";
  };
  "routes/staff.tsx": {
    id: "routes/staff";
    page: "/admin/staff";
  };
  "routes/staff-member.tsx": {
    id: "routes/staff-member";
    page: "/admin/staff/:id";
  };
  "routes/platform.tsx": {
    id: "routes/platform";
    page: "/platform";
  };
  "routes/search.ts": {
    id: "routes/search";
    page: "/search";
  };
  "routes/search-results.tsx": {
    id: "routes/search-results";
    page: "/search/results";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding/:kind/:ref";
  };
  "routes/orbit-console.tsx": {
    id: "routes/orbit-console";
    page: "/orbit/console";
  };
  "routes/orbit-save.tsx": {
    id: "routes/orbit-save";
    page: "/orbit/save";
  };
  "routes/orbit-pipeline.tsx": {
    id: "routes/orbit-pipeline";
    page: "/orbit/pipeline";
  };
  "routes/orbit-quality.tsx": {
    id: "routes/orbit-quality";
    page: "/orbit/quality";
  };
  "routes/orbit-analytics.tsx": {
    id: "routes/orbit-analytics";
    page: "/orbit/analytics";
  };
  "routes/north-brief.tsx": {
    id: "routes/north-brief";
    page: "/north/brief";
  };
  "routes/scout-radar.tsx": {
    id: "routes/scout-radar";
    page: "/scout/radar";
  };
  "routes/scout-panel.tsx": {
    id: "routes/scout-panel";
    page: "/scout/panel";
  };
  "routes/axis-exceptions.tsx": {
    id: "routes/axis-exceptions";
    page: "/axis/exceptions";
  };
  "routes/axis-board.tsx": {
    id: "routes/axis-board";
    page: "/axis/board";
  };
  "routes/axis-quote-desk.tsx": {
    id: "routes/axis-quote-desk";
    page: "/axis/quote-desk";
  };
  "routes/axis-doc-intel.tsx": {
    id: "routes/axis-doc-intel";
    page: "/axis/doc-intelligence";
  };
  "routes/axis-document-file.tsx": {
    id: "routes/axis-document-file";
    page: "/axis/documents/:id/file";
  };
  "routes/axis-analytics.tsx": {
    id: "routes/axis-analytics";
    page: "/axis/analytics";
  };
  "routes/axis-admin.tsx": {
    id: "routes/axis-admin";
    page: "/axis/admin";
  };
  "routes/axis-dev.tsx": {
    id: "routes/axis-dev";
    page: "/axis/dev";
  };
  "routes/axis-process-map.tsx": {
    id: "routes/axis-process-map";
    page: "/axis/process-map";
  };
  "routes/fnol-intake.tsx": {
    id: "routes/fnol-intake";
    page: "/axis/claims/new";
  };
  "routes/claims-desk.tsx": {
    id: "routes/claims-desk";
    page: "/axis/claims/desk";
  };
  "routes/renewal-desk.tsx": {
    id: "routes/renewal-desk";
    page: "/axis/renewals";
  };
  "routes/signal-cockpit.tsx": {
    id: "routes/signal-cockpit";
    page: "/signal/cockpit";
  };
  "routes/signal-studio.tsx": {
    id: "routes/signal-studio";
    page: "/signal/studio";
  };
  "routes/signal-audience-value.tsx": {
    id: "routes/signal-audience-value";
    page: "/signal/audience-value";
  };
  "routes/signal-answer-engines.tsx": {
    id: "routes/signal-answer-engines";
    page: "/signal/answer-engines";
  };
  "routes/signal-budget.tsx": {
    id: "routes/signal-budget";
    page: "/signal/budget";
  };
  "routes/signal-analytics.tsx": {
    id: "routes/signal-analytics";
    page: "/signal/analytics";
  };
  "routes/customer-360.tsx": {
    id: "routes/customer-360";
    page: "/admin/customers/:id/360";
  };
  "routes/product-detail.tsx": {
    id: "routes/product-detail";
    page: "/admin/products/:id/detail";
  };
  "routes/policy-detail.tsx": {
    id: "routes/policy-detail";
    page: "/axis/policies/:id/detail";
  };
  "routes/policy-endorse.tsx": {
    id: "routes/policy-endorse";
    page: "/axis/policies/:id/endorse";
  };
  "routes/policy-cancel.tsx": {
    id: "routes/policy-cancel";
    page: "/axis/policies/:id/cancel";
  };
  "routes/claim-detail.tsx": {
    id: "routes/claim-detail";
    page: "/axis/claims/:id/detail";
  };
  "routes/case-evidence-download.tsx": {
    id: "routes/case-evidence-download";
    page: "/axis/cases/:id/evidence-bundles/:bundleId/download";
  };
  "routes/case-detail.tsx": {
    id: "routes/case-detail";
    page: "/axis/cases/:id/detail";
  };
  "routes/channel-detail.tsx": {
    id: "routes/channel-detail";
    page: "/distribution/channels/:id/detail";
  };
  "routes/orbit-journey.tsx": {
    id: "routes/orbit-journey";
    page: "/orbit/journeys/:id/builder";
  };
  "routes/module.tsx": {
    id: "routes/module";
    page: "/:module";
  } | {
    id: "module-resource";
    page: "/:module/:resource";
  };
  "routes/record.tsx": {
    id: "routes/record";
    page: "/:module/:resource/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/portal.$tenantSlug": typeof import("./app/routes/portal.$tenantSlug.tsx");
  "routes/workspace": typeof import("./app/routes/workspace.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/approvals": typeof import("./app/routes/approvals.tsx");
  "routes/ai-console": typeof import("./app/routes/ai-console.tsx");
  "routes/ai-budget": typeof import("./app/routes/ai-budget.tsx");
  "routes/ai-run": typeof import("./app/routes/ai-run.tsx");
  "routes/cost-explorer": typeof import("./app/routes/cost-explorer.tsx");
  "routes/ledger-reports": typeof import("./app/routes/ledger-reports.tsx");
  "routes/ledger-money-map": typeof import("./app/routes/ledger-money-map.tsx");
  "routes/ledger-open-txn": typeof import("./app/routes/ledger-open-txn.tsx");
  "routes/ledger-transaction": typeof import("./app/routes/ledger-transaction.tsx");
  "routes/ledger-periods": typeof import("./app/routes/ledger-periods.tsx");
  "routes/ledger-account": typeof import("./app/routes/ledger-account.tsx");
  "routes/ledger-recon": typeof import("./app/routes/ledger-recon.tsx");
  "routes/analytics-report": typeof import("./app/routes/analytics-report.tsx");
  "routes/analytics-dashboard": typeof import("./app/routes/analytics-dashboard.tsx");
  "routes/quote-compare": typeof import("./app/routes/quote-compare.tsx");
  "routes/conversation": typeof import("./app/routes/conversation.tsx");
  "routes/commission-statement": typeof import("./app/routes/commission-statement.tsx");
  "routes/commission-clawback": typeof import("./app/routes/commission-clawback.tsx");
  "routes/dist-offers": typeof import("./app/routes/dist-offers.tsx");
  "routes/compliance-run": typeof import("./app/routes/compliance-run.tsx");
  "routes/settlement": typeof import("./app/routes/settlement.tsx");
  "routes/settlement-detail": typeof import("./app/routes/settlement-detail.tsx");
  "routes/admin-roles": typeof import("./app/routes/admin-roles.tsx");
  "routes/admin-developer": typeof import("./app/routes/admin-developer.tsx");
  "routes/admin-security": typeof import("./app/routes/admin-security.tsx");
  "routes/staff": typeof import("./app/routes/staff.tsx");
  "routes/staff-member": typeof import("./app/routes/staff-member.tsx");
  "routes/platform": typeof import("./app/routes/platform.tsx");
  "routes/search": typeof import("./app/routes/search.ts");
  "routes/search-results": typeof import("./app/routes/search-results.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/orbit-console": typeof import("./app/routes/orbit-console.tsx");
  "routes/orbit-save": typeof import("./app/routes/orbit-save.tsx");
  "routes/orbit-pipeline": typeof import("./app/routes/orbit-pipeline.tsx");
  "routes/orbit-quality": typeof import("./app/routes/orbit-quality.tsx");
  "routes/orbit-analytics": typeof import("./app/routes/orbit-analytics.tsx");
  "routes/north-brief": typeof import("./app/routes/north-brief.tsx");
  "routes/scout-radar": typeof import("./app/routes/scout-radar.tsx");
  "routes/scout-panel": typeof import("./app/routes/scout-panel.tsx");
  "routes/axis-exceptions": typeof import("./app/routes/axis-exceptions.tsx");
  "routes/axis-board": typeof import("./app/routes/axis-board.tsx");
  "routes/axis-quote-desk": typeof import("./app/routes/axis-quote-desk.tsx");
  "routes/axis-doc-intel": typeof import("./app/routes/axis-doc-intel.tsx");
  "routes/axis-document-file": typeof import("./app/routes/axis-document-file.tsx");
  "routes/axis-analytics": typeof import("./app/routes/axis-analytics.tsx");
  "routes/axis-admin": typeof import("./app/routes/axis-admin.tsx");
  "routes/axis-dev": typeof import("./app/routes/axis-dev.tsx");
  "routes/axis-process-map": typeof import("./app/routes/axis-process-map.tsx");
  "routes/fnol-intake": typeof import("./app/routes/fnol-intake.tsx");
  "routes/claims-desk": typeof import("./app/routes/claims-desk.tsx");
  "routes/renewal-desk": typeof import("./app/routes/renewal-desk.tsx");
  "routes/signal-cockpit": typeof import("./app/routes/signal-cockpit.tsx");
  "routes/signal-studio": typeof import("./app/routes/signal-studio.tsx");
  "routes/signal-audience-value": typeof import("./app/routes/signal-audience-value.tsx");
  "routes/signal-answer-engines": typeof import("./app/routes/signal-answer-engines.tsx");
  "routes/signal-budget": typeof import("./app/routes/signal-budget.tsx");
  "routes/signal-analytics": typeof import("./app/routes/signal-analytics.tsx");
  "routes/customer-360": typeof import("./app/routes/customer-360.tsx");
  "routes/product-detail": typeof import("./app/routes/product-detail.tsx");
  "routes/policy-detail": typeof import("./app/routes/policy-detail.tsx");
  "routes/policy-endorse": typeof import("./app/routes/policy-endorse.tsx");
  "routes/policy-cancel": typeof import("./app/routes/policy-cancel.tsx");
  "routes/claim-detail": typeof import("./app/routes/claim-detail.tsx");
  "routes/case-evidence-download": typeof import("./app/routes/case-evidence-download.tsx");
  "routes/case-detail": typeof import("./app/routes/case-detail.tsx");
  "routes/channel-detail": typeof import("./app/routes/channel-detail.tsx");
  "routes/orbit-journey": typeof import("./app/routes/orbit-journey.tsx");
  "routes/module": typeof import("./app/routes/module.tsx");
  "module-resource": typeof import("./app/routes/module.tsx");
  "routes/record": typeof import("./app/routes/record.tsx");
};