// Fills docs/traceability.csv from the evidence that actually exists, then
// prints the scorecard. A requirement is only marked `verified` here if a named
// test asserts it — docs/24 §Continuous: "Do not mark anything ☑ without a test
// or evidence reference." Everything else stays `not_started`, because a
// traceability matrix that flatters the build is worse than none.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CSV = resolve(ROOT, "docs/traceability.csv");
const VERIFIED_AT = process.env.VERIFIED_AT ?? "2026-07-30";
const VERIFIED_BY = "build";

const J = "apps/api/src/journeys.test.ts";
const API = "apps/api/src/api.test.ts";
const RBAC = "packages/core/src/rbac.test.ts";
const CORE = "packages/core/src/core.test.ts";
const COMM = "packages/core/src/commission.test.ts";
const SEED = "packages/core/src/seed.test.ts";
const LEDGER = "packages/ledger/src/ledger.test.ts";
const GW = "packages/model-gateway/src/gateway.test.ts";
const SHELL = "apps/web/app/shell.test.ts";

/** req_id -> [spec_ref, test_ref, evidence_ref] */
const MAP = {
  /* Journeys — one describe block per J-ID, all green. */
  "JRN-C1": ["docs/06 §2", `${J}::J-C1`, "apps/api/src/routes/dist.ts shop+comparison"],
  "JRN-C2": ["docs/06 §2", `${J}::J-C2`, "apps/api/src/routes/ai.ts runs + ai_audit_log"],
  "JRN-C3": ["docs/06 §2", `${J}::J-C3`, "orbit_renewals requote + accept"],
  "JRN-C4": ["docs/06 §2", `${J}::J-C4`, "apps/api/src/routes/compliance.ts DSAR"],
  "JRN-O1": ["docs/06 §2", `${J}::J-O1`, "axis cases/tasks + axis.bind approval"],
  "JRN-O2": ["docs/06 §2", `${J}::J-O2`, "group census shop + comparison"],
  "JRN-O3": ["docs/06 §2", `${J}::J-O3`, "ledger recon runs + exceptions"],
  "JRN-X1": ["docs/06 §2", `${J}::J-X1`, "orbit handover notes + qa scores"],
  "JRN-X2": ["docs/06 §2", `${J}::J-X2`, "axis.price_match + dist.settlement_run dual control"],
  "JRN-X3": ["docs/06 §2", `${J}::J-X3`, "dist.partner_activate approval + channel issue"],
  "JRN-M1": ["docs/06 §2", `${J}::J-M1`, "signal audiences/campaigns/creatives"],
  "JRN-M2": ["docs/06 §2", `${J}::J-M2`, "signal.budget_move approval + reversal"],
  "JRN-M3": ["docs/06 §2", `${J}::J-M3`, "signal aeo pages + citation runs"],
  "JRN-P1": ["docs/06 §2", `${J}::J-P1`, "scout whitespace promote + discovery run"],
  "JRN-P2": ["docs/06 §2", `${J}::J-P2`, "scout panel bench + dist.rate_change approval"],
  "JRN-E1": ["docs/06 §2", `${J}::J-E1`, "north briefings generated by analyst, read by exec"],
  "JRN-E2": ["docs/06 §2", `${J}::J-E2`, "north boardpacks + decisions"],
  "JRN-E3": ["docs/06 §2", `${J}::J-E3`, "north scenarios + analytics run"],
  "JRN-A1": ["docs/06 §2", `${J}::J-A1`, "tenant provisioning + brand/entitlements"],
  "JRN-A2": ["docs/06 §2", `${J}::J-A2`, "user invite + role bundle bounds"],
  "JRN-A3": ["docs/06 §2", `${J}::J-A3`, "agent pause/resume + autonomy approval + incident"],
  "JRN-D1": ["docs/06 §2", `${J}::J-D1`, "api keys issued, never read back"],
  "JRN-CO1": ["docs/06 §2", `${J}::J-CO1`, "masked vs unmasked analytics export"],

  /* Roles — each persona drives its own journey with its real grant bundle. */
  "ROLE-003": ["docs/06 §1", `${J}::J-A1,J-A2`, "tenant.admin seat in seed"],
  "ROLE-004": ["docs/06 §1", `${J}::J-CO1,J-C4`, "tenant.compliance seat in seed"],
  "ROLE-005": ["docs/06 §1", `${J}::J-C1,J-O1`, "axis.agent seat in seed"],
  "ROLE-006": ["docs/06 §1", `${J}::J-O1,J-C1`, "axis.lead share + bind authority"],
  "ROLE-008": ["docs/06 §1", `${J}::J-X1`, "orbit.agent seat in seed"],
  "ROLE-010": ["docs/06 §1", `${J}::J-C3,J-X2`, "orbit.retention save desk"],
  "ROLE-011": ["docs/06 §1", `${J}::J-X3`, "orbit.partners certify"],
  "ROLE-014": ["docs/06 §1", `${J}::J-M1,J-M2`, "signal.lead budget approval"],
  "ROLE-017": ["docs/06 §1", `${J}::J-P1,J-P2`, "scout.lead thresholds + panel"],
  "ROLE-019": ["docs/06 §1", `${J}::J-E1,J-E2,J-E3`, "north.exec seat in seed"],
  "ROLE-020": ["docs/06 §1", `${J}::J-E1`, "north.analyst generates the briefing"],
  "ROLE-021": ["docs/06 §1", `${RBAC}::keeps north.board read-only`, "packages/core/src/rbac.ts"],
  "ROLE-024": ["docs/06 §1", `${J}::J-D1`, "dev.admin key issue"],
  "ROLE-030": [
    "docs/06 §1",
    `${RBAC}::grants only permissions that exist;${API}::every string the API checks is a real permission`,
    "authz matrix over the whole registry"
  ],

  /* Platform. */
  "PLAT-002": ["docs/02 §3", `${API}::scopes every query to the caller's tenant`, "apps/api/src/engines/report.ts"],
  "PLAT-003": [
    "docs/02 §3",
    `${RBAC}::denies across tenants before looking at permissions;${CORE}::keeps another tenant's audit rows out of the chain`,
    "packages/core/src/rbac.ts, audit.ts"
  ],
  "PLAT-019": [
    "docs/12 §4",
    `${RBAC}::masks PII behind core:pii:view;${CORE}::masks for actors without core:pii:view`,
    "packages/core/src/pii.ts"
  ],
  "PLAT-031": ["docs/03 §5", `${CORE}::gates purposes and channels, and honours expiry`, "core_consents ledger"],
  "PLAT-033": ["docs/03 §5", `${J}::J-C1 shop without consent is refused`, "apps/api/src/routes/dist.ts"],
  "PLAT-051": ["docs/04 §7", `${CORE}::writes an outbox row and dedupes per consumer`, "core_event_inbox"],
  "PLAT-052": ["docs/04 §7", `${CORE}::writes an outbox row and dedupes per consumer`, "core_outbox"],
  "PLAT-079": ["docs/05 §7", `${J}::J-A3`, "apps/api/src/routes/ai.ts pause/resume + killswitch permission"],
  "PLAT-086": ["docs/12 §6", `${CORE}::chains rows and detects tampering`, "packages/core/src/audit.ts hash chain"],
  "PLAT-096": [
    "docs/04 §6",
    `${CORE}::requires an approval, then honours it;${J}::J-X2 dual control`,
    "packages/core/src/approvals.ts"
  ],
  "PLAT-095": ["docs/12 §2", `${CORE}::never auto-approves client money, whatever the tenant policy says`, "neverAutoApprove"],
  "PLAT-101": ["docs/07 §2", `${SHELL}::keeps en and ar on exactly the same keys`, "apps/web/app/i18n"],

  /* Security. */
  "SEC-004": ["docs/12 §3", `${API}::refuses an unknown dataset;${J}::J-C1 no-consent 400`, "zod .strict() on every body"],
  "SEC-006": ["docs/12 §3", `${GW}::destroys secrets rather than placeholding them`, "packages/model-gateway/src/scrub.ts"],
  "SEC-016": ["docs/12 §5", `${GW}::scrubs outbound, rehydrates inbound and audits the call`, "context builder whitelist"],
  "SEC-017": [
    "docs/12 §5",
    `${GW}::blocks a regulated claim on a customer-facing purpose and still bills it`,
    "guardrail classifier"
  ],
  "SEC-024": ["docs/12 §7", `${J}::J-A3`, "kill switch pause/resume audited"],

  /* Ledger and transactions. */
  "TXN-002": [
    "docs/19 §3",
    `${LEDGER}::replaying a transaction with the same key posts nothing new;${LEDGER}::a second batch for the same transaction is a conflict, not a duplicate`,
    "packages/ledger/src/txn.ts idempotency key"
  ],
  "TXN-003": ["docs/19 §3", `${LEDGER}::refuses an illegal transition`, "packages/ledger/src/txn.ts state machine"],
  "TXN-004": [
    "docs/19 §3",
    `${LEDGER}::returns net-zero economics and leaves the original intact;${LEDGER}::refuses to reverse the same batch twice`,
    "contra-only corrections"
  ],
  "TXN-007": ["docs/19 §3", `${LEDGER}::a failed step unwinds the ones before it`, "saga compensation"],
  "TXN-033": ["docs/19 §4", `${GW}::charges usage and hard-stops at 100%`, "packages/model-gateway/src/budget.ts"],
  "TXN-050": ["docs/19 §5", `${LEDGER}::holds for every financial transaction type, fuzzed`, "double-entry property test"],
  "TXN-054": [
    "docs/19 §5",
    `${LEDGER}::1010 >= 2010 after any random sequence of client-money transactions`,
    "client-money invariant, property-tested"
  ],
  "TXN-055": [
    "docs/19 §5",
    `${LEDGER}::rejects the illegal shape directly;${LEDGER}::no recipe in the catalogue produces the illegal shape`,
    "packages/ledger/src/postings.ts"
  ],
  "TXN-056": ["docs/19 §5", `${LEDGER}::refuses a posting that would take client money below the liability`, "hard block"],
  "TXN-061": ["docs/19 §6", `${LEDGER}::nets to zero even when FX left a rounding residual`, "FX stamp at posting"],
  "TXN-063": [
    "docs/19 §6",
    `${LEDGER}::blocks a posting into a hard-closed period unless it is a contra batch;${LEDGER}::will not hard close straight from open`,
    "period lifecycle"
  ],
  "TXN-064": ["docs/19 §6", `${LEDGER}::the balances cache agrees with a rebuild from lines`, "trial balance"],

  /* Analytics. */
  "ANL-016": ["docs/22 §5", `${API}::hashes a PII dimension unless the caller is entitled`, "unmasked export approval"]
};

// The CSV is CRLF (exported from a sheet); split on both and write CRLF back so
// the diff is the status columns only, not every line ending in the file.
const lines = readFileSync(CSV, "utf8").split(/\r?\n/);
const TAIL = ",,,,not_started,,";
let filled = 0;

const out = lines.map((line) => {
  const id = line.slice(0, line.indexOf(","));
  const e = MAP[id];
  if (!e || !line.endsWith(TAIL)) return line;
  filled++;
  return (
    line.slice(0, -TAIL.length) +
    [",", q(e[0]), ",", q(e[1]), ",", q(e[2]), ",verified,", VERIFIED_BY, ",", VERIFIED_AT].join("")
  );
});
writeFileSync(CSV, out.join("\r\n"));

/** CSV quoting: a field with a comma or a quote must be quoted, quotes doubled. */
function q(v) {
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

/* ------------------------------------------------------------- scorecard */

const rows = out.slice(1).filter(Boolean).map(parse);
const byPrefix = new Map();
for (const r of rows) {
  const p = r.id.split("-")[0];
  const s = byPrefix.get(p) ?? { must: 0, verified: 0, total: 0 };
  s.total++;
  if (r.priority === "M") s.must++;
  if (r.status === "verified" && r.priority === "M") s.verified++;
  byPrefix.set(p, s);
}
console.log(`filled ${filled} rows\n`);
console.log("prefix  verified/must  total");
let must = 0;
let ver = 0;
for (const [p, s] of [...byPrefix].sort()) {
  must += s.must;
  ver += s.verified;
  console.log(`${p.padEnd(7)} ${String(s.verified).padStart(4)}/${String(s.must).padEnd(5)} ${String(s.total).padStart(5)}`);
}
console.log(`\nTOTAL   ${ver}/${must} Must verified (${Math.round((ver / must) * 100)}%)`);

/** Minimal CSV row split — enough for id/priority/status, which are never multiline. */
function parse(line) {
  const cells = [];
  let cur = "";
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQ) {
      if (ch === '"' && line[i + 1] === '"') (cur += '"'), i++;
      else if (ch === '"') inQ = false;
      else cur += ch;
    } else if (ch === '"') inQ = true;
    else if (ch === ",") (cells.push(cur), (cur = ""));
    else cur += ch;
  }
  cells.push(cur);
  return { id: cells[0], priority: cells[2], status: cells[9] };
}
